version: '3.8'

services:

  redis:
    image: redis:7-alpine

  web:
    container_name: web
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A CollectImmobilien worker -l INFO
    volumes:
      - app:/app
    environment:
      - DEBUG=1

      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
volumes:
  app:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: .