version: '3.8'

services:

  redis:
    image: redis:7-alpine

  django:
    container_name: django
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A CollectImmobilien worker -l INFO
    volumes:
      - app:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django

  celeryworker:
    container_name: celeryworker
    build:
      context: ./celeryworker
    command: celery -A celerytasks worker -l INFO
    volumes:
      - celery:/app
    depends_on:
      - redis
      - django

volumes:
  app:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: .
  celery:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./celeryworker