version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celeryworker:
    container_name: celeryworker
    build:
      context: ./celeryworker
    command: celery -A celerysetup worker -l INFO -Q celery,posttasks,scrapingtasks,dead_letter -B
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=worker1
      - OTEL_LOG_LEVEL=DEBUG
    volumes:
      - celery:/app
    depends_on:
      - redis
      - rabbitmq

  db:
    image: postgis/postgis:17-3.5-alpine
    container_name: db
    hostname: db
    env_file:
      - .env
    ports:
      - "5432:5432"

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.5
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PBF_PATH=/nominatim/data/berlin-brandenburg-241218.osm.pbf
      - IMPORT_STYLE=address
    shm_size: 256m
    volumes:
      - ./osm-maps/data:/nominatim/data
      - nominatim-data:/var/lib/postgresql/16/main


volumes:
  nominatim-data:
    driver: local
  celery:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./celeryworker