version: '3.8'

services:

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"

  redis:
    image: redis:7-alpine

  django:
    container_name: django
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - app:/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=django,localhost,127.0.0.1
    depends_on:
      - redis
      - db

  celeryworker:
    container_name: celeryworker
    build:
      context: ./celeryworker
    command: celery -A celerysetup worker -l INFO -Q celery,tasks,dead_letter -B
    env_file:
      - .env
    volumes:
      - celery:/app
    depends_on:
      - redis
      - django
      - rabbitmq

  db:
    image: postgres:16-alpine
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    shm_size: 2gb
    environment:
      - SE_ENABLE_TRACING=false
    ports:
     - "4444:4444"

volumes:
  app:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: .
  celery:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./celeryworker
  db-data:
    driver: local
