# Generated by Django 5.1.3 on 2025-01-15 11:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImmobilienResource',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('crawler', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Immobilie',
            fields=[
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('map_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('price', models.IntegerField()),
                ('provider', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('plot', 'plot'), ('house', 'house')], max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.immobilienresource')),
            ],
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('immobilie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.immobilie')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('districts', models.ManyToManyField(to='core.district')),
            ],
        ),
        migrations.AddField(
            model_name='immobilie',
            name='regions',
            field=models.ManyToManyField(blank=True, to='core.region'),
        ),
    ]
